### ISSUE TITLE
:No module named chumpy.reordering

### ISSUE THREAD

**Issue by HUTHG** [boukhayma/3dhand#6]
I got the error trace below after run "python tester.py"

Traceback (most recent call last):
  File "tester_modified.py", line 5, in <module>
    from model import resnet34_Mano
  File "/home/tianhang/Documents/3dhand-master/3dhand-master/model.py", line 18, in <module>
    dd = pickle.load(open('mano/models/MANO_RIGHT.pkl', 'rb'))
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named chumpy.reordering

I updated my pickle package, and do have the latest MANO_RIGHT.pkl file in directory, 
 

I am running system in 

Linux 16.04, 
python==2.7
pickle == 2.0

and download MANO in http://mano.is.tue.mpg.de/

Does it indicates there is something wrong with the MANO package I download?

**Comment by almond2008** [comment]
pip install chumpy
